#!/usr/bin/env bash
SIP_LATEST_VERSION='sip-4.18.1.tar.gz'
SIP_DIR='sip-4.18.1'
PYQT_LATEST_VERSION='PyQt-x11-gpl-4.11.4.tar.gz'
PYQT_DIR='PyQt-4.11.4'
SIP_URL='http://downloads.sourceforge.net/project/pyqt/sip/'$SIP_DIR
PYQT_URL='http://downloads.sourceforge.net/project/pyqt/PyQt4/'$PYQT_DIR
DOWNLOAD_PATH='/tmp/pyqt'

function clean {
  mkdir -p $DOWNLOAD_PATH;
  rm -rf $DOWNLOAD_PATH/*
}

function get_sip {
  echo -e "\n\nDownloading SIP..."
  wget $SIP_URL/$SIP_LATEST_VERSION
}

function get_pyqt {
  echo -e "\n\nDownloading PyQt..."
  wget $PYQT_URL/$PYQT_LATEST_VERSION
}

function build_sip {
  echo -e "\n\nBuilding SIP..."
  tar xf $SIP_LATEST_VERSION
  pushd $SIP_DIR > /dev/null
  $PYTHON configure.py -e $VIRTUAL_ENV/include && make && make install
  popd > /dev/null
  echo "SIP was successfully built!"
}

function build_pyqt {
  echo -e "\n\nBuilding PyQt..."
  if [ ! -d $PYQT_DIR ];
  then
    mkdir $PYQT_DIR
  fi
  tar xf $PYQT_LATEST_VERSION -C $PYQT_DIR --strip-components=1
  pushd $PYQT_DIR > /dev/null
  $PYTHON configure.py --confirm-license --no-designer-plugin --no-qsci-api && make && make install
  popd > /dev/null
  echo "PyQt was successfully built!"
}

function init_envs {
  source ./$1/bin/activate
  if [ -z $1 ];
  then
      echo "Usage: install_pyqt.sh VIRTUALENV_NAME"
      exit 1
  fi
  pushd $DOWNLOAD_PATH > /dev/null
  PYTHON=$VIRTUAL_ENV/bin/python
}

function cleanup {
  if [ -z $VIRTUAL_ENV ];
    then
      deactivate
  fi
}

clean && init_envs $1
set -e
(get_sip && build_sip && get_pyqt && build_pyqt && $PYTHON -c "import sip, PyQt4" && cleanup && echo "Install finished!") || (cleanup && echo "Install failed")
popd > /dev/null
